[package]
name = "indexer-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
indexer = { path = "../indexer" }
alloy = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }